### ISSUE TITLE
group by pod (perhaps with submenu)

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [rgolangh/gnome-shell-extension-containers#38]
when using podman pods, the extension lists them all at once

it would be nice to group them

instead of ![gnome-containers-apod](https://user-images.githubusercontent.com/156838/171370505-09151933-1327-499e-a963-1f2595216bf6.png)

something like ![gnome-containers-apod-new](https://user-images.githubusercontent.com/156838/171370501-3d31772f-fe29-4bf4-ad48-7e8228257ff4.png) or even having all of them listed in the submenu

**Comment by rgolangh** [comment]
I played with pod idea while ago, and unfortunately nested submenu in a submenu was not easily achieved (at the time I tried). I'll check on that again.

But your mockup (thanks for that btw!) made me think that a visual separation, even though not a submenu(that you can fold), would be still handy.
Another idea, have a button that makes the menu list pods instead of containers. And then you start/stop the pod (and that would stop its containers)
