### ISSUE TITLE
feature suggestions

### ISSUE THREAD

**Issue by idnovic** [rgolangh/gnome-shell-extension-containers#6]
Here are a few feature suggestions

Add a feature that opens a terminal and connects to inside the container
`-it ` Connect the container to the (gnome)terminal
(_podman exec container command_)

`podman restart container` Restart container, add between pause and stop

`--name name` Give the container a name, makes it simpler to differentiate containers with with same source image 

`podman inspect container` Return metadata (in JSON) about a running container (clipboard)

`podman stats container` Display a live stream of a container’s resource usage (terminal?)
`podman top container` Display the running processes of a container (terminal?)
`podman logs [-tail] container` Display the logs of a container (terminal?)

**Comment by rgolangh** [comment]
Thanks for the suggestions!

> Add a feature that opens a terminal and connects to inside the container
-it Connect the container to the (gnome)terminal
(podman exec container command)

This one is fantastic, love it, and I think the most useful one from the list. 

> podman restart container Restart container, add between pause and stop

Makes sense actually + a fairly easy one.

> podman inspect container Return metadata (in JSON) about a running container (clipboard)

I'm not sure how useful is that, because I tend to think that if users need the JSON, they probably want to filter and extract something, and this means typing on the CLI and maybe this will not make the whole operation quicker. Do you have a scenario in mind?

> podman stats container Display a live stream of a container’s resource usage (terminal?)
podman top container Display the running processes of a container (terminal?)
podman logs [-tail] container Display the logs of a container (terminal?)

I wonder maybe all of these could invoke a gnome-shell output widget of its own.

**Comment by rgolangh** [comment]
The only two suggestion which are not part of the fixes are the `--name` and the `inspect` json.
If you still think those are necessary please open a separate issues for them.
